name: 'Jira 이슈 생성'
description: 'Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
labels: [feature]

body:
  - type: input
    id: dueDate
    attributes:
      label: '🗓️ 마감일'
      placeholder: '2025-07-03'
    validations:
      required: true

  - type: dropdown
    id: assignee
    attributes:
      label: '🙋 담당자(Assignee)'
      options:
        - g0rnn
        - seobeeeee1001
    validations:
      required: true
      
  - type: input
    id: parentKey
    attributes:
      label: '🎟️ 상위 작업의 Ticket Number를 입력해주세요.'
      description: '이 하위 작업이 속할 상위 작업의 Ticket Number를 입력해주세요 (예: WT-12).'
      placeholder: 'WT-12'
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: '📝 상세 내용(Description)'
      description: '이슈에 대해서 간략히 설명해주세요'
    validations:
      required: false

  - type: textarea
    id: tasks
    attributes:
      label: '✅ 작업 목록(Tasks)'
      description: '해당 이슈에 대해 필요한 작업 목록을 작성해주세요'
      value: |
        - [ ] Task1

    validations:
      required: true
