name: Create Jira Issue on GitHub Issue

on:
  issues:
    types: 
        - opened

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          
      - name: Checkout main code
        uses: actions/checkout@v4
        with:
            ref: main
            
      - name: Issue Parser
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/jira-issue-form.yml
        
      - name: Map GitHub username to Jira accountId
        id: assignee
        run: |
          echo '${{ secrets.JIRA_USER_MAP }}' > user_map.json
          FORM_ASSIGNEE="${{ steps.issue-parser.outputs.issueparser_assignee }}"
          ACCOUNT_ID=$(jq -r --arg user "$FORM_ASSIGNEE" '.[$user]' user_map.json)
      
          echo "Resolved accountId for $FORM_ASSIGNEE → $ACCOUNT_ID"
          echo "accountId=$ACCOUNT_ID" >> $GITHUB_OUTPUT

      - name: Convert markdown to Jira Syntax
        uses: peter-evans/jira2md@v1
        id: md2jira
        with:
          input-text: |
            ### Github Issue Link
            - ${{ github.event.issue.html_url }}

            ${{ github.event.issue.body }}

      - name: Build fields JSON
        id: issue-fields
        run: |
          PARENT_STORY_KEY="${{ steps.issue-parser.outputs.issueparser_parentKey }}"
          DUE_DATE="${{ steps.issue-parser.outputs.issueparser_dueDate }}"
          ASSIGNEE_ID="${{ steps.assignee.outputs.accountId }}"
          DESCRIPTION="${{ steps.md2jira.outputs.output-text }}"

          FIELDS=$(jq -nc \
            --arg parent "$PARENT_STORY_KEY" \
            --arg description "$DESCRIPTION" \
            --arg assignee "$ASSIGNEE_ID" \
            '{
              parent: { key: $parent },
              description: $description,
              assignee: { id: $assignee }
            }'
          )

          [ -n "$DUE_DATE" ] && FIELDS=$(echo "$FIELDS" | jq --arg duedate "$DUE_DATE" -c '. + { duedate: $duedate }')

          echo "fields=$FIELDS" >> $GITHUB_OUTPUT

    
      - name: Create Jira Issue
        if: startsWith(steps.issue-parser.outputs.issueparser_parentKey, 'WT-')
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: WT
          issuetype: Sub-task
          summary: '${{ github.event.issue.title }}'
          description: '${{ steps.md2jira.outputs.output-text }}'
          fields: '${{ steps.issue-fields.outputs.fields }}'

      - name: Log created issue
        if: steps.create.outputs.issue != ''
        run: echo "Jira Issue ${{ steps.create.outputs.issue }} was created"

      - name: Create branch with Ticket number
        run: |
              GITHUB_ISSUE_NUMBER="${{ github.event.issue.number }}"
        
              git checkout -b ${{ steps.create.outputs.issue }}
              git push origin ${{ steps.create.outputs.issue }}

      - name: Define ISSUE_NUMBER fallback
        run: |
          echo "ISSUE_NUMBER=${{ steps.create.outputs.issue }}" >> $GITHUB_ENV

      - name: Update GitHub Issue Title
        if: steps.create.outputs.issue != ''
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          JIRA_ISSUE_KEY="${{ steps.create.outputs.issue }}"
          NEW_TITLE="${ISSUE_TITLE}(${JIRA_ISSUE_KEY})"
          echo "NEW_TITLE=${NEW_TITLE}" >> $GITHUB_ENV

      - name: Apply new title
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          title: '${{ env.NEW_TITLE }}'

      - name: Add comment with Jira issue link
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: 'Jira Issue Created: [${{ env.ISSUE_NUMBER }}](${{ secrets.JIRA_BASE_URL }}/browse/${{ env.ISSUE_NUMBER }})'
